### ISSUE TITLE
There are 2 var 'name' declared

### ISSUE THREAD

**Issue by ghost** [rubenwardy/report#1]
There are 2 var name declared https://github.com/rubenwardy/report/blob/master/init.lua#L21

func = function(**name**, param)
....for _, player in pairs(minetest.get_connected_players()) do
.........local **name** = player:get_player_name()
.........if minetest.check_player_privs(**name**, {kick = true, ban = true}) then
................table.insert(mods, **name**)
................minetest.chat_send_player(**name**, "-!- " .. **name** .. " reported: " .. param)
........end
....end
end

**Comment by rubenwardy** [comment]
Thank you for alert me to this. A silly mistake.

https://github.com/rubenwardy/report/commit/aa0c84399557c811caf2efa07013ce1245b35878
